name             'wordpress-cluster'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures a high availability wordpress cluster'
long_description 'Installs/Configures a high availability wordpress cluster'
version          '0.1.0'

depends 'apt'
depends 'yum'
depends 'git'
depends 'hg'
depends 'unzip'
depends 'ssh-import-id'
depends 'capistrano-wordpress'
depends 'haproxy'
depends 'consul'
depends 'consul-cluster'
depends 'consul-services'
depends 'consul-template'
depends 'lsyncd'
depends 'csync2'
depends 'keepalived'
